version: "2.4"

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16
          gateway: 172.21.0.1
services:
  postgres-currency:
    image: postgres:latest
    mem_limit: 1024m
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - C:/logs/postgres-currency:/var/lib/postgresql/data
  # hostname
  currency-converter:
    image: currency-converter:2.0.0
    #### ! ####
    mem_limit: 512m
    # environment variables
    environment:
      DB_URL: ${POSTGRES_URL}
      DB_USERNAME: postgres
      DB_PASSWORD: mysecretpassword
      API_KEY: ${API_KEY}
      PORT: 8080
    volumes:
      - C:/logs/currency-converter:/logs
    ports:
      - "8080:8080"
    # when depends_on is used, the container will wait for the other container to be ready
    depends_on:
      - postgres-currency
    restart: always
#  angular-frontend:
#     image: angular-currency:1.0.0
#     ports:
#       - "4200:80"
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf
#     restart: always