server:
  port: ${PORT:8080}

spring:
  datasource:
    type: org.postgresql.jdbc2.optional.SimpleDataSource
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:mysecretpassword}
    url: ${DB_URL:jdbc:postgresql://localhost:5433/software}

    jpa:
      hibernate:
        ddl-auto: update

api:
  key: ${API_KEY:myapikey}

exchangerate:
  key: ${EXCHANGE_RATE_KEY:myapikey}

keycloak:
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL:http://localhost:8081/}
  autodetect-bearer-only: true
  credentials:
    secret: 4R4pdQ2gf28nh9ZFDUCNjFh9jSd8aUVQ
  realm: software
  resource: backend
  ssl-required: none
  use-resource-role-mappings: false
  security-constraints:
    - auth-roles:
        - ADMIN
      security-collections:
        - name: ADMINS
          omitted-methods:
            - OPTIONS
          patterns:
            - /api/v1/conversions/all
    - auth-roles:
        - USER
      security-collections:
        - name: Conversion
          omitted-methods:
            - OPTIONS
          patterns:
            - /api/v1/conversions